### PR TITLE
Image classification topologies corrected for Neon 2.2 and Neon 2.3

### PR DESCRIPTION
**Pull request by tpatejko**
All_cnn, Alexnet, Googlenet and Alexnet work with Neon 2.3 and Aeon 1.0.
DeepResnet works with Neon 2.2 due to errors related to bias fusion (?)

### CODE REVIEW

**Comment by tpatejko** [comment]
DeepResnet on Neon 2.3 gives the following error:

> File"resnet_eval.py", line 63, in <module>
> model = Model(load_obj(args.model_file), weights_only=True)
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/models/model.py", line 70, in init
> self.deserialize(layers, load_states=(not weights_only))
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/models/model.py", line 475, in deserialize
> self.layers.load_weights(model_dict['model'], load_states)
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/layers/container.py", line 202, in load_weights
> branch.load_weights(bdict, load_states=load_states)
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/layers/container.py", line 202, in load_weights
> branch.load_weights(bdict, load_states=load_states)
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/layers/container.py", line 198, in load_weights
> pdict['config']['layers'] = self.fusion_pass(pdict['config']['layers'])
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/layers/container.py", line 177, in fusion_pass
> if any([pattern(l1, l2) for pattern in patterns]):
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/layers/container.py", line 172, in <lambda>
> y['type'] == 'neon.layers.layer.Bias']
> TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by wei-v-wang** [comment]
Thanks @tpatejko for the PR. 
Regarding DeepResnet failure, could you please try the code pattern discussed in https://github.com/NervanaSystems/neon/issues/415 ?
i.e. can you try to re-write Model(load_obj(args.model_file), load_states)
to 
Model (...)
model.load_params(args.model_file, load_states)? 

Also, could you please take a look at https://github.com/NervanaSystems/modelzoo/tree/VGG_neon2.3 to merge the best ingredients of the two for VGG? 

Thank you!

File: ImageClassification/ILSVRC2012/Alexnet/test.sh [hunk 1]
```diff
@@ -22,7 +22,7 @@ WEIGHTS_FILE=${WEIGHTS_URL##*/}
 echo "Downloading weights file from ${WEIGHTS_URL}"
 curl -o $WEIGHTS_FILE $WEIGHTS_URL 2> /dev/null
 
-python -u alexnet_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /usr/local/data/I1K/macrobatches/ -vvv --model_file $WEIGHTS_FILE --no_progress_bar | tee output.dat 2>&1
+python -u alexnet_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /data/i1k-extracted/ --manifest_root /data/i1k-extracted --manifest train:/data/i1k-extracted/train-index.csv --manifest val:/data/i1k-extracted/val-index.csv -vvv --model_file $WEIGHTS_FILE --no_progress_bar  -z 256 | tee output.dat 2>&1
```
Comment (baojun-nervana) [inline ImageClassification/ILSVRC2012/Alexnet/test.sh]: can you use "/dataset/aeon/I1K/i1k-extracted/" instead of "/data/i1k-extracted/" to be consistent with validation dataset structure?

File: ImageClassification/CIFAR10/DeepResNet/test.sh [hunk 2]
```diff
@@ -23,14 +23,14 @@ WEIGHTS_FILE=${WEIGHTS_URL##*/}
 echo "Downloading weights file from ${WEIGHTS_URL}"
 curl -o $WEIGHTS_FILE $WEIGHTS_URL 2> /dev/null
 
-python -u $TEST_SCRIPT  -i ${EXECUTOR_NUMBER} -vvv --model_file $WEIGHTS_FILE --no_progress_bar -w /usr/local/data/CIFAR10/macrobatches | tee output.dat 2>&1
+python -u $TEST_SCRIPT  -i ${EXECUTOR_NUMBER} -vvv --model_file $WEIGHTS_FILE --manifest val:/data/CIFAR/val-index.csv --manifest_root /data/CIFAR -b gpu -z 32 --no_progress_bar 2>&1 | tee output.dat
```
Comment (baojun-nervana) [inline ImageClassification/CIFAR10/DeepResNet/test.sh:26]: can you use "/dataset/aeon/CIFAR10" instead of "/data/CIFAR"?

File: ImageClassification/ILSVRC2012/Alexnet/test.sh [hunk 3]
```diff
@@ -22,7 +22,7 @@ WEIGHTS_FILE=${WEIGHTS_URL##*/}
 echo "Downloading weights file from ${WEIGHTS_URL}"
 curl -o $WEIGHTS_FILE $WEIGHTS_URL 2> /dev/null
 
-python -u alexnet_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /usr/local/data/I1K/macrobatches/ -vvv --model_file $WEIGHTS_FILE --no_progress_bar | tee output.dat 2>&1
+python -u alexnet_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /data/i1k-extracted/ --manifest_root /data/i1k-extracted --manifest train:/data/i1k-extracted/train-index.csv --manifest val:/data/i1k-extracted/val-index.csv -vvv --model_file $WEIGHTS_FILE --no_progress_bar  -z 256 2>&1 | tee output.dat
```
Comment (baojun-nervana) [inline ImageClassification/ILSVRC2012/Alexnet/test.sh:25]: can you use "/dataset/aeon/I1K/i1k-extracted" instead of "/data/i1k-extracted"?

File: ImageClassification/ILSVRC2012/Googlenet/test.sh [hunk 4]
```diff
@@ -22,7 +22,7 @@ WEIGHTS_FILE=${WEIGHTS_URL##*/}
 echo "Downloading weights file from ${WEIGHTS_URL}"
 curl -o $WEIGHTS_FILE $WEIGHTS_URL 2> /dev/null
 
-python -u googlenet_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /usr/local/data/I1K/macrobatches/ -vvv --model_file $WEIGHTS_FILE --no_progress_bar | tee output.dat 2>&1
+python -u googlenet_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /data/i1k-extracted --manifest_root /data/i1k-extracted --manifest val:/data/i1k-extracted/val-index.csv -vvv --model_file $WEIGHTS_FILE --no_progress_bar 2>&1 | tee output.dat
```
Comment (baojun-nervana) [inline ImageClassification/ILSVRC2012/Googlenet/test.sh:25]: can you use "/dataset/aeon/I1K/i1k-extracted" instead of "/data/i1k-extracted"?

File: ImageClassification/ILSVRC2012/VGG/test.sh [hunk 5]
```diff
@@ -22,7 +22,8 @@ WEIGHTS_FILE=${WEIGHTS_URL##*/}
 echo "Downloading weights file from ${WEIGHTS_URL}"
 curl -o $WEIGHTS_FILE $WEIGHTS_URL 2> /dev/null
 
-python -u vgg_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /usr/local/data/I1K/macrobatches/ -vvv --model_file $WEIGHTS_FILE --no_progress_bar  -z 64 --vgg_version E | tee output.dat 2>&1
+python -u vgg_neon.py --test_only -i ${EXECUTOR_NUMBER} -w /data/i1k-extracted -vvv --manifest_root /data/i1k-extracted --manifest val:/data/i1k-extracted/val-index.csv --model_file $WEIGHTS_FILE --no_progress_bar -z 64 --vgg_version E 2>&1 | tee output.dat
```
Comment (baojun-nervana) [inline ImageClassification/ILSVRC2012/VGG/test.sh:25]: can you use "/dataset/aeon/I1K/i1k-extracted" instead of "/data/i1k-extracted"?

**Comment by tpatejko** [comment]
@wei-v-wang Thanks for your comment

I tried to change the script following your remarks but I have a problem with the following part of code:
> Model (...)
> model.load_params(args.model_file, load_states)

but I'm not quite sure how to initialize Model part. I tried to use code that builds model in file resnet_cifar10.py but I encountered the following error:
> File "/home/tpatejko/_aeon/ModelZoo/neon_2.3/neon/layers/container.py", line 200, in load_weights
 >   assert len(pdict['config']['layers']) == len(self.layers)

Another question: could you elaborate on what you mean by merging best ingredients of two for VGG?

File: ImageClassification/CIFAR10/DeepResNet/test.sh (hunk 2 above)
Comment (tpatejko) [reply ImageClassification/CIFAR10/DeepResNet/test.sh:26]: @baojun-nervana Out of curiosity, is there any particular reason why these paths should be changed?

Comment (baojun-nervana) [reply ImageClassification/CIFAR10/DeepResNet/test.sh:26]: @tpatejko that is the validation dataset directory, so we don't have to update those after the PR.

**Comment by wei-v-wang** [comment]
@tpatejko Sorry I must have missed your comments above. 

I will take a look at the resnet_eval failure. 

For VGG, I just create a PR to modelZoo as well. https://github.com/NervanaSystems/ModelZoo/pull/25 

Thanks!

File: ImageClassification/CIFAR10/All_CNN/readme.md [hunk 6]
```diff
@@ -13,7 +13,7 @@ The trained weights file can be downloaded from AWS
 
 
 ### neon version
-The model weight file above has been generated using neon version tag [v1.4.0]((https://github.com/NervanaSystems/neon/releases/tag/v1.4.0).
+The model weight file above has been generated using neon version tag [v2.3.0]((https://github.com/NervanaSystems/neon/releases/tag/v2.3.0).
```
Comment (wei-v-wang) [inline ImageClassification/CIFAR10/All_CNN/readme.md:16]: "The mode weight file" will probably need to be converted to new format. Have you already obtained a trained weight with neon v2.2/v2.3 format?

File: ImageClassification/ILSVRC2012/Alexnet/alexnet_neon.py [hunk 7]
```diff
@@ -105,15 +135,15 @@
 
 # configure callbacks
 valmetric = TopKMisclassification(k=5)
-callbacks = Callbacks(model, eval_set=test, metric=valmetric, **args.callback_args)
+callbacks = Callbacks(model, eval_set=val, metric=valmetric, **args.callback_args)
 
 if args.model_file is not None:
     model.load_params(args.model_file)
```
Comment (wei-v-wang) [inline ImageClassification/ILSVRC2012/Alexnet/alexnet_neon.py]: model.load_params(args.model_file) should work. Why does resnet_eval.py in cifar10 does not support this. 
We can see alexnet support this.

File: ImageClassification/CIFAR10/DeepResNet/resnet_eval.py [hunk 8]
```diff
@@ -15,24 +15,50 @@
...
+            'etl': [image_config, label_config],
+            'augmentation': [augmentation]}
+
+def make_val_config(manifest_filename, manifest_root, batch_size, subset_pct=100):
+    val_config = config(manifest_filename, manifest_root, batch_size, subset_pct)
+    return wrap_dataloader(AeonDataLoader(val_config))
+
+test_set = make_val_config(args.manifest["val"], args.manifest_root, batch_size=args.batch_size)
 
 model = Model(load_obj(args.model_file))
```
Comment (wei-v-wang) [inline ImageClassification/CIFAR10/DeepResNet/resnet_eval.py:63]: model=Model(load_obj(args.model_file)) will break the code, since neon v2.2 and v2.3 was not supposed to initialize a model using old weights. model=Model(load_obj(args.model_file) works with new weights. 
So how do we get the new format of an old args.model_file. 
Can we try to use model=Model(layers=cifar10_layers). 
And do model.load_params(args.model_files, load_state).. 

When we see there is an assert failure. This usually mean only a subset of the cifar10 layers was involved in saving the weights. So we need to print out those layer information from the old weight file and see which layers are missing. We then delete those layers (temporarily) from cifar10 layers.

File: ImageClassification/ILSVRC2012/Googlenet/googlenet_neon.py [hunk 9]
```diff
@@ -122,16 +148,16 @@ def aux_branch(bnode):
                  weights=[1, 0., 0.])  # We only want to consider the CE of the main path
 
 assert os.path.exists(args.model_file), 'script requires the trained weights file'
-model.load_params(args.model_file)
-model.initialize(test, cost)
+model.load_params(args.model_file, load_states=False)
+model.initialize(val, cost)
```
Comment (wei-v-wang) [inline ImageClassification/ILSVRC2012/Googlenet/googlenet_neon.py:152]: In general, not specific to this task, 
what is the difference between validation and test? 
Normally we do training + validation. And then we do test with test dataset, right? 
It seems neon has only being using training dataset and validation dataset for testing, not test dataset.

File: ImageClassification/ILSVRC2012/VGG/vgg_neon.py [hunk 10]
```diff
@@ -83,10 +117,10 @@
 
 # configure callbacks
 top5 = TopKMisclassification(k=5)
-callbacks = Callbacks(model, eval_set=test, metric=top5, **args.callback_args)
+callbacks = Callbacks(model, eval_set=val, metric=top5, **args.callback_args)
 
-model.load_params(args.model_file)
-mets=model.eval(test, metric=TopKMisclassification(k=5))
+model.load_params(args.model_file, load_states=False)
+mets=model.eval(val, metric=TopKMisclassification(k=5))
```
Comment (wei-v-wang) [inline ImageClassification/ILSVRC2012/VGG/vgg_neon.py:123]: This vgg_neon.py seems to be only the inference path. 
Is it OK to merge your VGG changes to https://github.com/NervanaSystems/ModelZoo/pull/25? 
Or merge changes in https://github.com/NervanaSystems/ModelZoo/pull/25 to this PR is also OK.

Comment (wei-v-wang) [reply ImageClassification/ILSVRC2012/VGG/vgg_neon.py:123]: PR #25 has both training + inference and updated readme.

**Review by wei-v-wang — DISMISSED** [review]

File: ImageClassification/CIFAR10/DeepResNet/test.sh (hunk 2 above)
Comment (wei-v-wang) [reply ImageClassification/CIFAR10/DeepResNet/test.sh:26]: Changed

File: ImageClassification/ILSVRC2012/Alexnet/test.sh (hunk 3 above)
Comment (wei-v-wang) [reply ImageClassification/ILSVRC2012/Alexnet/test.sh:25]: Changed

File: ImageClassification/ILSVRC2012/Googlenet/test.sh (hunk 4 above)
Comment (wei-v-wang) [reply ImageClassification/ILSVRC2012/Googlenet/test.sh:25]: Changed

File: ImageClassification/ILSVRC2012/VGG/test.sh (hunk 5 above)
Comment (wei-v-wang) [reply ImageClassification/ILSVRC2012/VGG/test.sh:25]: changed

**Comment by wei-v-wang** [comment]
@tpatejko Can you please work on uploading the new formatted weight files to aws first?

File: ImageClassification/CIFAR10/All_CNN/readme.md (hunk 6 above)
Comment (wei-v-wang) [reply ImageClassification/CIFAR10/All_CNN/readme.md:16]: Assuming yes.

File: ImageClassification/CIFAR10/DeepResNet/resnet_eval.py (hunk 8 above)
Comment (wei-v-wang) [reply ImageClassification/CIFAR10/DeepResNet/resnet_eval.py:63]: Is resnet_eval.py still functional/successful in loading weights?

**Review by wei-v-wang — COMMENTED** [review]
Overall looks good. Need to upload new weights to aws and verify resnet_cifar10 functionality.
